---
- name: Assert that we are not logged in as root
  assert:
    that:
      - ansible_user_id != 'root'
    fail_msg: "Podman containers are rootless, so please do not run this role as root."

- name: Assert all configuration variables have been defined.
  ansible.builtin.assert:
    that:
      - item.value is defined
      - item.value != ''
    fail_msg: "FAILED: Required configuration settings are not configured. Passwords cannot be blank."
    quiet: true
  no_log: true
  with_dict: "{{ castopod_config }}"

- import_tasks: setup.yml
- import_tasks: podman.yml
- import_tasks: systemd.yml

- name: "(Workaround) Copy /var/www/castopod/public from container to host"
  ansible.builtin.command:
    cmd: "podman cp castopod:/var/www/castopod/public {{ castopod_web_root }}"
  changed_when: false

- name: "(Workaround) Set ownership of {{ castopod_web_root }}"
  ansible.builtin.command:
    cmd: "chown -R 1000:nginx {{ castopod_web_root }}"
  become: yes